### ISSUE TITLE
resources to address What is psych safety

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/seaside-chat-psychological-safety#1]
This repo and site give me so much joy!

To address [your note](https://openscapes.github.io/seaside-chat-psychological-safety/#what-is-psychological-safety), Openscapes Lesson Series, core lesson on [Team Culture](https://openscapes.github.io/series/core-lessons/team-culture.html) has resources with citations for psychological safety ✨

**Comment by rmarow** [comment]
Added one link in this commit 4c54c0c. Will add more !

**Comment by rmarow** [comment]
Another resource added a3879f0

**Comment by rmarow** [comment]
closing since links were added :)
